
Transaction.create(business_day_id: 1 , client: "Andy Spade", product_id: 1)
Transaction.create(business_day_id: 1, client: "Kate Walsh", product_id: 2)
Transaction.create(business_day_id: 1, client: "Jane Walsh", product_id: 5)
Transaction.create(business_day_id: 1, client: "Kate Stewart", product_id: 4)
Transaction.create(business_day_id: 1, client: "Brooke Bryan", product_id: 3)
Transaction.create(business_day_id: 1, client: "Diego Dorado", product_id: 2)
Transaction.create(business_day_id: 1, client: "Ed Helms", product_id: 1)
Transaction.create(business_day_id: 1, client: "Bradley Cooper", product_id: 2)
Transaction.create(business_day_id: 1, client: "Zach Gal", product_id: 6)
Transaction.create(business_day_id: 2, client: "Jake Walsh", product_id: 7)
Transaction.create(business_day_id: 2, client: "Kate Edwards", product_id: 3)
Transaction.create(business_day_id: 2, client: "Nicole Same", product_id: 2)
Transaction.create(business_day_id: 2, client: "Janet Jackson", product_id: 1)
Transaction.create(business_day_id: 2, client: "Wanda Fleming", product_id: 3)
Transaction.create(business_day_id: 2, client: "Elaine Barry", product_id: 4)
Transaction.create(business_day_id: 2, client: "Kate Smart", product_id: 5)

Business_Day.create(date: "08/01/2017")
Business_Day.create(date: "08/02/2017")
Business_Day.create(date: "08/03/2017")
Business_Day.create(date: "08/04/2017")
Business_Day.create(date: "08/05/2017")
Business_Day.create(date: "08/06/2017")
Business_Day.create(date: "08/07/2017")

Product.create(name: "Leather Jacket", department: "Clothing", cost: 998)
Product.create(name: "Fit & Flare Dress", department: "Clothing", cost: 598)
Product.create(name: "Cigarette Pants", department: "Clothing", cost: 398)
Product.create(name: "Blouse", department: "Clothing", cost: 275)
Product.create(name: "Necklace", department: "Jewelry", cost: 250)
Product.create(name: "Wallet", department: "Accessories", cost: 350)
Product.create(name: "Hobo", department: "Accessories", cost: 998)
